# Generated by Django 4.2.4 on 2023-08-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='icon',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
