# Generated by Django 4.2.4 on 2023-08-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_app_icon_alter_tech_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
